// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://xxcpdphqpayaclzinrji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4Y3BkcGhxcGF5YWNsemlucmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxODQxOTMsImV4cCI6MjA5NDc2MDE5M30.mz3IUvOr6n2BNR1ZvhCquXHC8S0fZ7m-BeDNtil4GsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
