// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qzwyglmymncuxztgpvor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6d3lnbG15bW5jdXh6dGdwdm9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTI0MjUsImV4cCI6MjA3NDQ2ODQyNX0.hzlB3rkAQlFXGQdxdq6BF3s8sFTWyhcg0_xgQh09zkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);